### ISSUE TITLE
Need a consistent success or failure response behavior

### ISSUE THREAD

**Issue by PropGit** [dbetz/proploader#10]
There's a least one case where the response is not clear; did it succeed or did it fail?

For example, a successful module naming request (-n switch) simply returns control to the command line, without giving any notice.  And a wireless discovery request (-W) gives no response when nothing is found.  Though the discovery operation did finish properly, it represents a failure to find any module, yet the response is the same as a successful naming operation.

The lack of a _success_ message is fine, but to be clear to the user, let's add a "No modules found" response to a discovery request that doesn't find any modules, and add a similar response behavior to any other operations that may present a similar conflicting response.

**Comment by dbetz** [comment]
I don't interpret finding no modules as an error. The request is to list all available modules and it seems to me that "none" is a successful response if there are none to be found.

**Comment by PropGit** [comment]
Under the circumstances, having the naming feature respond when successful (with the actual name applied to the module) will satisfy this concern.
