### ISSUE TITLE
Retrieve Parallax Wi-Fi Firmware version?

### ISSUE THREAD

**Issue by PropGit** [dbetz/proploader#12]
Do we have a way to wirelessly retrieve the firmware version of the Parallax Wi-Fi Firmware?

If not, can we implement one (through proploader)?

**Comment by dbetz** [comment]
There is a way to retrieve any information that you see on the ESP configuration screens. That's how the web interface works. In fact, I didn't have to do anything on the ESP side to implement the -n option in proploader that sets the friendly name. I just used the same HTTP request that the ESP configuration screens use. I believe there is a version number that can be retrieved. I'll check to see what the exact HTTP request is that is required.

**Comment by dbetz** [comment]
There is an HTTP request /menu that returns a JSON response in the following form:

{ "menu": [ "Home", "/home.html", "WiFi Station", "/wifi/wifiSta.html", "WiFi Soft-AP", "/wifi/wifiAp.html", "&#xb5;C Console", "/console.html", "Services", "/services.html", "REST/MQTT", "/mqtt.html", "Debug log", "/log.html" ], "version": "esp-link master - 2016-04-01 10:24:25 - development", "name": "My Module" }

The "version" field contains the version string displayed on the ESP configuration page.
