### ISSUE TITLE
Explore timeout before "connect failed"

### ISSUE THREAD

**Issue by PropGit** [dbetz/proploader#14]
I experienced a delay > 20 or 30 seconds before the _connect failed_ message in the following results:

```
Loading 'LargeSpinCodePABWX.binary'
Loading second-stage loader
connect failed    <-- major delay before this message arrived
error: connect failed
error: set-baud-rate request failed
error: load failed: -1
```

Note: The module was having occasional loss of association near this time, which may account for the extra delay; however, if we could shorten the timeout to something more reasonable (thinking there's no possibility of recovery after a certain short period (seconds)), that would be wonderful.

**Comment by dbetz** [comment]
The connect() socket function doesn't seem to have a timeout parameter. I'll have to check to see how a timeout can be specified for it.

**Comment by PropGit** [comment]
Maybe there's no was to adjust this, and I can't tell if it's directly related to that either; just pointing out something that we may be able to optimize.  If any part of the communication has reached a point of no return, significant additional delay before the user can try something else only leads to user frustration.

**Comment by dbetz** [comment]
Changed the connect timeout for HTTP requests to 2 seconds.
