### ISSUE TITLE
Two truncation possibilities are not caught by image verification

### ISSUE THREAD

**Issue by PropGit** [dbetz/proploader#22]
There are two truncated (or bad) file possibilities that are not caught properly.  These are exhibited by the files in the archive: [BAD_BINARIES.ZIP](https://github.com/parallaxinc/PropLoader/files/649773/BAD_BINARIES.ZIP)

### Case 1
With the file __PABWX-Blink#1_bad_length_1.binary__, all data beyond byte 15 is missing (file size is 16 bytes).  Expected message code 110, but instead get message code 111.

Similarly, the file __PABWX-Blink#1_bad_length_1b.binary__ is the same as above except with the checksum set proper for the actual data in the file.  This results in no error, where it should actually result in message code 110.

### Case 2
With the file __PABWX-Blink#1_bad_length_2.binary__, the last byte of the file is missing (file size is 47 bytes) making it one byte less than specified by vbase (word 4), yet this results in no error message when message code 110 was expected.

NOTE: When the file is < 16 bytes, the message code 110 does indeed appear as expected.

**Comment by dbetz** [comment]
Case 1
Are you just saying that the test for error 110 should be that the file size is <= 16 rather than just < 16?

Case 2
Are you saying I should be checking for "idx != m_imageSize" rather than "idx < m_imageSize" given the algorithm you gave me for checking for bytes beyond the end of the code?

**Comment by PropGit** [comment]
Case 1
That's not what I was meaning, but you just made me realize that it should indeed be checking for "<= 16" and, if that is false, should also check for the file size being less than the value in word 4.  If either of those conditions are true, it should stop and generate the 110 error.

Case 2
No, Case 2 should also be caught by the logic in Case 1 as described above.

**Comment by dbetz** [comment]
Word 4 is what my code calls "vbase"? It would be nice to have some standard names for these header fields rather than just referring to them as numeric word offsets.

**Comment by PropGit** [comment]
Yes, it's vbase.  I'll try to use the names rather than locations from now on (if there is a name).

**Comment by dbetz** [comment]
This is the structure that proploader uses. Please let me know if there is anything incorrect about it.

```
/* spin object file header */
typedef struct {
    uint32_t clkfreq;
    uint8_t clkmode;
    uint8_t chksum;
    uint16_t pbase;
    uint16_t vbase;
    uint16_t dbase;
    uint16_t pcurr;
    uint16_t dcurr;
} SpinHdr;
```

**Comment by PropGit** [comment]
Yes, that's correct.

**Comment by PropGit** [comment]
Tested v1.0-18.  Verified all above cases are correct now.
