### ISSUE TITLE
Image Verification breaks File To SD feature

### ISSUE THREAD

**Issue by PropGit** [dbetz/proploader#24]
The binary image verification enhancements added recently are applied also to the File-to-SD feature... that caused that feature to fail.  Please prevent that image verification from happening when it's trying to load a file to SD.

From SimpleIDE's Build Status during File-to-SD:

```
proploader.exe -p COM23 -f techloop.wavOpening file 'techloop.wav'
ERROR: File is corrupt or not a Propeller application
```

**Comment by dbetz** [comment]
I think this might be a different problem from what you think. To write a file to the SD card I have to download a helper program. It is probably that program that is being flagged as corrupt. I'll have to check to see why that is happening. It is just an array of bytes from a .binary file so it should be okay. I'm not sure what's going wrong.

**Comment by dbetz** [comment]
Never mind. You were right. I've just pushed a fix.

**Comment by dbetz** [comment]
This is fixed I believe. Can it be closed?

**Comment by PropGit** [comment]
Yes, I'll close it now.
