### ISSUE TITLE
Add Reset Signal (DTR or RTS) option

### ISSUE THREAD

**Issue by PropGit** [dbetz/proploader#25]
The PropLoader currently delivers the Propeller Reset signal on the logical DTR pin (of both the wired serial ports and the wireless Wi-Fi ports).

Please add a command-line option to deliver the Propeller Reset signal to either the DTR or RTS pin of the given port (wired serial or wireless Wi-Fi).

NOTE: This issue became a bit more complicated than anticipated... it has been [resized in this post, below](https://github.com/parallaxinc/PropLoader/issues/25#issuecomment-293063471).

**Comment by dbetz** [comment]
Added a config variable "reset" that can be set to "dtr" (default) or "rts". In addition, it can be set to "gpioN" for Raspberry Pi builds and a numeric pin number for wi-fi loading.

To use RTS for reset add this to the proploader command line:

-D reset=rts

**Comment by PropGit** [comment]
@dbetz - I don't understand why Raspberry Pi builds of PropLoader need the gpioN feature.  And does that mean, for example: -D reset=gpio13  in order to cause the reset signal to be generated on gpio pin 13?

**Comment by dbetz** [comment]
Yes, that is correct. This is for serial downloads only.

**Comment by PropGit** [comment]
Due to problems with RTS pin (causing Wi-Fi module freeze on power-up if RTS is high), we need to redirect the reset signal to CTS instead of RTS on the Wi-Fi module.  However, RTS is still valid for serial loads.

We need "-D reset=dtr" or "-D reset=rts" to work for serial ports (USB ports).
We need "-D reset=dtr" or "-D reset=cts" to work for wireless ports (Wi-Fi Module ports).

Can we accommodate the above possibilities conveniently, and with added error messages if the wrong option is used for the wrong port type?  i.e.: Error if RTS requested for Wi-Fi port / CTS requested for serial port?

**Comment by dbetz** [comment]
The WX firmware is currently setup to ignore the setting of "-D reset=xxx" and just use whatever the user selected on the configuration web page. As far as the serial loader goes, it only accepts "dtr" and "rts" unless it is running on a RaspberryPi in which case it also recognizes "gpioN".

**Comment by PropGit** [comment]
I see.  Okay, then it sounds like the loader is already in a state we need it in and we just need to update the WX firmware to accept CTS (and handle it properly) according to the issue we wrote up for that.

This issue can be closed now, right?

**Comment by dbetz** [comment]
I think so.

**Comment by dbetz** [comment]
However, we might want to remove the code from proploader that sets the resetpin parameter in the HTTP load requests since it won't have any effect anyway.

**Comment by PropGit** [comment]
Okay, yes, good point... please remove the code that sets the resetpin parameter in the HTTP load requests.

**Comment by PropGit** [comment]
Verified PropLoader v1.0-33 (2017-04-22 08:49:27 g0d30b50) properly programs the Propeller over Wi-Fi SIP (when configured to deliver Reset Signal via the CTS pin).

Was the code ever removed that tries to set the resetpin parameter in the HTTP load request?  I think that's the only reason this issue remains open.

**Comment by dbetz** [comment]
No, I haven't removed the code in proploader yet. However, the -D option on the command line that is used to set the reset pin is a generic option that can be used to set any config setting and it is needed for setting the reset pin for a RaspberryPi. I won't remove -D. I'll just ignore the reset-pin setting when doing a wi-fi load and not pass it as part of the URL. The change will be transparent to users since they never see the URL anyway.

**Comment by PropGit** [comment]
Closing.
