### ISSUE TITLE
RAM and EEPROM checksum verification timeouts

### ISSUE THREAD

**Issue by PropGit** [dbetz/proploader#36]
What are the timeout periods for waiting for RAM Checksum response and EEPROM Checksum response?

Are those timeouts different (internally in PropLoader) for wired vs. wireless, or are they somehow related?

These questions arise because the timeout for EEPROM Checksum response is much too long, greater than 20 seconds.  This is testable on wired serial by downloading and pressing/releasing the reset button right after "Programming EEPROM" message appears.

**Comment by PropGit** [comment]
The timeout seems somehow related to the transmitPacket routine retry cycles, according to the verbose messages.  Perhaps this isn't a very practical thing to trim down.

**Comment by dbetz** [comment]
It depends on which load you mean. For loading the second-stage loader using the Propeller ROM loader the timeout for the checksum is 250ms, the timeout for EEPROM programming is 5s and the timeout for EEPROM verify is 2s.

If you're talking about loading the user program, the timeout for programming the EEPROM is 8s but the code tries three times.
