### ISSUE TITLE
Add logic and message to alert when RAM checksum failed

### ISSUE THREAD

**Issue by PropGit** [dbetz/proploader#37]
[This request created in response to Issue #27]

In much the same way that the added "Propeller not found" error message clarifies download failures, we need a RAM checksum failure message.

- Add fatal error message, "RAM checksum failed" and give it the next available error code.
- Add logic to emit that message when a RAM checksum response is received and doesn't match the proper value.
  - Note: doesn't apply if there's a fatal timeout waiting for RAM checksum response; that's handled by Issue #39.

This should apply to both wired and wireless downloads and should appear before the "ERROR: Download failed: -1" message so that instead of this:
```
001-Opening file '../myfile.binary'
002-Downloading file to port ...
009-... bytes sent
003-Verifying RAM
102-ERROR: Download failed: -1
```
we see this (assuming the error code is 124):
```
001-Opening file '../myfile.binary'
002-Downloading file to port ...
009-... bytes sent
003-Verifying RAM
124-ERROR: RAM checksum failed
102-ERROR: Download failed: -1
```

**Comment by dbetz** [comment]
I've added this to the fast loader code. It is not yet present in the single-stage loader.

**Comment by dbetz** [comment]
done

**Comment by PropGit** [comment]
Tested on v1.0-37.
