### ISSUE TITLE
RaspberryPi

### ISSUE THREAD

**Issue by ClockLoop** [dbetz/proploader#43]
Do you need someone to compile the raspberry pi proploader file?
I went to get the latest in the releases... but nope, i thought a pi version was maintained too.
I have done this and can provide the compiled file if no one else has a working chain, v1.0-37.

**Comment by ClockLoop** [comment]
I was told  "I'm pretty sure the Makefile can build a RaspberryPi version using the RaspberryPi cross tools."

I didn't know that, i can't find the list of makefile command combinations possible, and reading the makefile helps but i don't know the structure enough on how to piece the syntax together.
So still someone would need to make a working chain in any os to get the ability to have a pi executable, many don't and won't have that even if they are pi users.

**Comment by dbetz** [comment]
make CROSS=rpi

I do this on an Ubuntu system with the RaspberryPi cross compiler installed. I don't have a RaspberryPi setup to do it natively.
