### ISSUE TITLE
Confusing naming of loader variables (-D option)

### ISSUE THREAD

**Issue by rstemmer** [dbetz/proploader#47]
The naming scheme of the loader variables are not uniform which leads to misspelling and difficult to find bugs.

Current names:
```
 loader reset clkfreq clkmode fast-loader-clkfreq fastloader-clkmode baudrate loader-baud-rate fast-loader-baud-rate
```
Sometimes it is _fast-loader_, sometimes _fastloader_.
Sometimes _baudrate_, sometimes _baud-rate_.

Making the use of "-" for all variables the same will improve the interface tremendously.
To be backwards compatible it may be a good idea to just allow both variations, with and without "-".

**Comment by dbetz** [comment]
I just pushed a fix for this problem. The issue with "fastloader-clkmode" was just a help string problem. The variable is really called "fast-loader-clkmode" in the code. I've also added "baud-rate" as an option as well as keeping "baudrate" for backward compatibility. Thanks for reporting these problems.
