### ISSUE TITLE
Download request does not fail gracefully

### ISSUE THREAD

**Issue by PropGit** [dbetz/proploader#9]
When the target module does not exist, proploader continues through protocol even when it can't possibly succeed (download requests, name requests).  In addition, it takes > 42 seconds (on Windows) to finish the download request that has failed in this manner.

For example, when 192.168.1.118 doesn't exist, the command `proploader -i 192.168.1.118 PABWX-Blink#4.binary` causes the following response:

```
Loading 'PABWX-Blink#4.binary'
```

for 21 seconds.  Then the following:

```
connect failed
Loading second-stage loader
```

for another 21 seconds.  Then the following:

```
connect failed
error: connect failed
error: set-baud-rate request failed
error: load failed: -1
```

Please make it
- time-out much earlier (1 to 2 seconds) after no response to the connection request
- in the case of a download request - terminate the request upon delivering the first "connect failed" message, since success later in the protocol is impossible.

**Comment by dbetz** [comment]
Added a 2 second timeout for the target connection after which a load will fail.
